### ISSUE TITLE
FormatException("Invalid double", source)

### ISSUE THREAD

**Issue by alejopulidor** [LunaGao/flag_flutter#77]
Greetings, I have an error of type FormatException("Invalid double", source) when I try to use the flag of Colombia code CO, it works for me with the one of Mexico and some others

<img width="923" alt="image" src="https://user-images.githubusercontent.com/59415229/176055012-02478a6e-7131-427e-98b2-39b6c108648b.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/59415229/176054613-e92848db-4e5a-48f9-9453-3846dc1a0788.png">

Thank you for the package it has been very useful for me

**Comment by ollyde** [comment]
Also getting this randomly, like sometimes the flags show, sometimes they don't.

Many of the flags are broken:

<img width="341" alt="Screenshot 2022-06-30 at 11 18 39" src="https://user-images.githubusercontent.com/6940726/176641109-06092cfc-961d-42f9-9ad5-1386b926ba33.png">

**Comment by XiXiongMaoXiong** [comment]
> Greetings, I have an error of type FormatException("Invalid double", source) when I try to use the flag of Colombia code CO, it works for me with the one of Mexico and some others
> 
> <img alt="image" width="923" src="https://user-images.githubusercontent.com/59415229/176055012-02478a6e-7131-427e-98b2-39b6c108648b.png">
> 
> <img alt="image" width="287" src="https://user-images.githubusercontent.com/59415229/176054613-e92848db-4e5a-48f9-9453-3846dc1a0788.png">
> 
> Thank you for the package it has been very useful for me

I'm just here to say: I love your IDE colouring scheme

**Comment by iipavlov** [comment]
This is what I received as error:

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FormatException: Invalid double **1pt**.
....
       at SvgParserState.parse(parser_state.dart:887)
       at SvgParser.parse(parser.dart:27)
       at Svg.fromSvgString(svg.dart:139)
       at Svg.svgPictureStringDecoder(svg.dart:90)

In this case the issue was with the Tanzania's flag: `.... /flag-6.0.0./res/4x3/tz.svg`

In the source code of the svg there stays: 

<g fill-rule="evenodd" stroke-width="**1pt**" ....

Luckily this is the only occurence of 1pt in the file.

This could be a defect of the svg parser that doesn't accept units in the length value for stroke-width, but on a practical note maybe you should remove the units (there are also other files with units in the stroke-width)

**Comment by iipavlov** [comment]
It was solved for me with the new svg images from #78

**Comment by pauli2406** [comment]
use it like this for now:
```
flag:
  git:
    url: https://github.com/LunaGao/flag_flutter.git
    ref: stable
```

**Comment by linxydmhg** [comment]
It would be cool if the author could update the pub.dev package, as it's now 8 months old and does not work for many countries

**Comment by LunaGao** [comment]
published on pub.dev
